* Summary
=org-status= provides a simple mechanism for you to [[http://bit.ly/Moxggf][tweet]] from anywhere you have `org-mode' or can use =org-capture=. Currently, =org-status= only supports a single Twitter account. Your tweets can be written and stored in any =org-mode= file. 

* Configuration
1) Download and install =org-status.el= somewhere in your =load-path=.
1) Either download and install =org-status='s dependency [[http://bit.ly/MoxPqw][defhook]] or modify the =defhook= calls in the =org-status.el= so that it doesn't call =defhook=.
1) Download, install, and configure =t=, following the instructions at [[http://bit.ly/KGlf2s]].
1) In Emacs, customize the =org-status= group with the command =M-x customize-group= with the argument of =org-status=. You will likely need to change the =org-status-twitter-command= option to point to the installed path of =t=.
1) Optionally, create an =org-capture= template in by modifying the variable =org-capture-templates=. 
1) If you are unfamiliar with =org-capture=, you should probably glance at its [[http://bit.ly/MoC0m7][Capture documentation]].

* Authoring Your Tweets
Create one or more =org-mode= file that ends with =-status.org=. In the template above I use the file =~/Documents/my-status.org=. A tweet is any `org-mode' heading that has a tag of =TWEET= and the todo status of =POST=.
: * POST                                               :TWEET: 
:   This is the minimum for a tweet.

In addition to the prescribed minimum above, you can add more data to the tweet heading. I like to add a brief title as a summary in addition to the date.
: * POST Brilliant Title [2012-06-03 Sun 15:26]        :TWEET: 
:   This is a much richer tweet entry.

In general, you can add any additional information to the =org-mode= heading or to an =org-mode= [[http://orgmode.org/manual/Drawers.html][drawer]] associated with the heading.

This is the template that I use by adding it to =org-capture-templates=:
#+BEGIN_SRC emacs-lisp
("s" "Status" 
     entry (file+datetree "~/Documents/my-status.org") 
     "* POST %^{Title } %U :TWEET:\n%? %A\n" 
     :prepend nil :empty-lines nil)
#+END_SRC
 
In addition to adding extra data in the headings, it stores tweets in an =org-mode= =datetree=. Very handy.

Note: Do not nest one tweet within another. The results will be unpredictable and likely bad.

* Tweeting
Once you've authored one or more tweets, you publish them by saving the file that contains them. Because tweeting involves talking to Twitter's servers, saving the file can take several seconds for each tweet that must be published. 

When everything works correctly, you will get a buffer that contains the output from =t=. It tells you that the tweet was successful and gives you some information specific to =t=. If there is a problem, you will receive an error message. 

While I'm certain there are many more possible errors, the only ones that I've seen are:
  1) A tweet greater than 140 characters. If this happens, shorten your tweet.
  2) A network error if =t= can't connect to the Twitter servers. If this happens, try again to see if it is just a short-term problem with Twitter. If not, fix your network problems.
  3) A duplicate tweet error message from =t= if =t= feels that you are duplicating a tweet. When this happens, the first thing you should do is confirm that your tweet is a duplicate. If it is not a duplicate, file a bug on [[http://bit.ly/MoEmS6][t's issue page]]. If it is a duplicate tweet, then you must manually change the =POST= todo status to the =DONE= todo status. You can simply edit the tweet's heading or use =org-todo=, typically =\C-c\C-t=, to change the heading to done.

* Support
I encourage you to file bugs, questions, or suggestions on [[http://bit.ly/MoEKzO][org-status's issue page]]. No promises, but I'll do the best that I can. 

* Futures
Assuming I have the time, I would like to add more functionality to =org-status=. The top of my list of new features are
  - Add support for updating Facebook status.
  - Add support for updating Facebook Pages.
  - Add support for multiple Twitter accounts.

Please feel free to vote for your favorites or ask for other features using [[http://bit.ly/MoEKzO][org-status's issue page]]. 

# LocalWords:  datetree
